import '@/styles/globals.css'

import type { Metadata } from 'next'
import { Inter as FontSans, Rowdies as FontSecondary } from 'next/font/google'

import { i18n } from '@/i18n'
import { cn } from '@/libs/tw-merge'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

const fontSecondary = FontSecondary({
  subsets: ['latin'],
  weight: ['400', '300', '700'],
  variable: '--font-secondary',
})

export async function generateStaticParams() {
  const langs = i18n.locales.map((lang) => ({ lang }))
  return langs
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string }
}) {
  return (
    <html lang={params.lang}>
      <body
        className={cn(
          'min-h-screen bg-background font-sans text-foreground antialiased',
          fontSans.variable,
          fontSecondary.variable,
        )}
      >
        {children}
      </body>
    </html>
  )
}
