import '@/styles/globals.css'

import type { Metadata } from 'next'
import { Inter as FontSans, Mooli as FontSecondary } from 'next/font/google'

import { cn } from '@/libs/tw-merge'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

const fontSecondary = FontSecondary({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-secondary',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans text-foreground antialiased',
          fontSans.variable,
          fontSecondary.variable,
        )}
      >
        {children}
      </body>
    </html>
  )
}
